### ISSUE TITLE
What are the overall background objects called, in this program??

### ISSUE THREAD

**Issue by DerellLicht** [doug24/ThemeEditor#2]
I want to change the general background color of the controls area...
For example, the box that has 'All sizes' radio button in the upper-left corner...
Or the larger box that is labeled 'Search in' ... 
I don't see anything which actually sets those background colors; without that, the themes are not actually effective...

**Comment by doug24** [comment]
Yes, it is very poorly named:  "GradientBackground".   

The original themes use a LinearGradientBrush (which isn't editable in the Theme Editor).  You can edit the xaml file and change it to a SolidColorBrush and when you restart the Theme Editor, it will appear and be editable.

`	<SolidColorBrush x:Key="GradientBackground" po:Freeze="true" Color="#FF221810" />`

**Comment by DerellLicht** [comment]
> Yes, it is very poorly named: "GradientBackground".
> 
> The original themes use a LinearGradientBrush (which isn't editable in the Theme Editor). You can edit the xaml file and change it to a SolidColorBrush and when you restart the Theme Editor, it will appear and be editable.
> 
> ` <SolidColorBrush x:Key="GradientBackground" po:Freeze="true" Color="#FF221810" />`

Excellent!!  Thank you so much!!
So if I want to change anything else that has a LinearGradientBrush setting, I should first change it to SolidColorBrush, as we did here...

**Comment by doug24** [comment]
Yes, they have to be SolidColorBrushes to be editable in the Theme Editor.  They you can change them back if you want.

Any brush in the xaml file can be a solid or gradient brush.  There are also radial gradient brushes.  [link](https://learn.microsoft.com/en-us/dotnet/desktop/wpf/graphics-multimedia/painting-with-solid-colors-and-gradients-overview?view=netframeworkdesktop-4.8)

**Comment by DerellLicht** [comment]
Next question: What is the large data-results field called??
It is related to the Match* entries, but the default colors do not appear to be in the list...  
Foreground is #FFFFFF, background is #252525

**Comment by doug24** [comment]
It is a TreeView, so it uses the TreeView.* settings.

The match lighlights are as you have figured out the Match.* settings.

The preview window that shows the whole file is AvalonEdit.*

The circular buttons with an ^ or v arrow are Expanders

The Bookmarks dialog has a DataGrid control, which isn't in the Theme Editor.

**Comment by DerellLicht** [comment]
> It is a TreeView, so it uses the TreeView.* settings.
> 
> The match lighlights are as you have figured out the Match.* settings.
> 
> The preview window that shows the whole file is AvalonEdit.*
> 
> The circular buttons with an ^ or v arrow are Expanders
> 
> The Bookmarks dialog has a DataGrid control, which isn't in the Theme Editor.

Yeah, sorry about that... I should have recognized the TreeView control, I've used them in my own C++ programs...
Most of the others I recognize, but thank you for pointing out the Bookmarks dialog; I was wondering what DataGrid was!!

Okay, I think I have these settings clear now...
