### ISSUE TITLE
V1.1.0 - Missing system buttons

### ISSUE THREAD

**Issue by DerellLicht** [doug24/ThemeEditor#3]
Maximize/Minimize/Close icons are missing... 

![dnGrep Theme Editor bug](https://github.com/doug24/ThemeEditor/assets/5551606/05aefc1b-0c6a-44a9-a3ed-339de8dd0c91)

**Comment by doug24** [comment]
I think I know what happened here, I'll do another release when I've made some more changes.

From your comment on the other issue:  I will change the name of the AvalonEdit keys.  Not final yet, but I am thinking it will be 'PreviewText'.  The same control and colors are used in the Replace dialog.  I will also be adding new colors for the caption buttons when the window is inactive (from another user's request). While I'm doing that, I will make a couple of other changes to the themes - fix two misspellings, change a few keys, and add a couple of other new colors. I will post all the changes together when it is finalized.

**Comment by DerellLicht** [comment]
Excellent!!  Thank you very much, once again!!

I think PreviewText is perfect, users will absolutely understand what is being referred to...

It is a joy to watch a developer who is really committed to his product... "Yes, I'll fix that, while I'm at it, I'll get this also... oh wait, what is that??  I'll fix that too..."  It's sort of like a homeowner who accidentally cleans off one dusty surface, and then looks around... 

Thank you so much, once again, for your devotion to these products!!!

**Comment by doug24** [comment]
I just published a new release with lots of changes.  See this [discussion topic ](https://github.com/dnGrep/dnGrep/discussions/1066#discussioncomment-8687260)for a full list of changes to the theme files - you can either edit your theme with the new editor, or merge in changes from one of the theme files included in the release package.  You will not be able to view the changes in dnGrep until after the March 2024 release next week.

I'll update the Readme file on the main [Theme Editor](https://github.com/doug24/ThemeEditor/tree/v2.0.0) page soon.

**Comment by doug24** [comment]
Just wanted to add that you need to make the key name changes and add the new color elements to your theme file manually before opening it in the theme editor - it will not add the missing colors or fix the keys for you.

**Comment by DerellLicht** [comment]
In TE V2.0.1, this issue is fixed
