### ISSUE TITLE
TE V2.0.0 - cannot run program

### ISSUE THREAD

**Issue by DerellLicht** [doug24/ThemeEditor#4]
When I run the editor, I get an error message:
"You must install or update .NET to run this application"
under details, it says:
Required: 'Microsft.NETCore.App', version '8.0.0' (x64)

I clicked the "Download it now" button, which takes me to the MS .NET install page;
I downloaded and installed windowsdesktop-runtime-8.0.2-win-x64.exe from that page,
but I still get this error... perhaps it is because you used 8.0.0, but I updated to 8.0.2 ??

**Comment by doug24** [comment]
Using 8.0.2 should not be a problem, that is how Windows Update patches the .NET 8 runtime so anything built on .NET 8 should continue to run on the patch releases.

There may have been a problem with a build setting I had in the project, so I just uploaded a new zip file in the v2.0.1 release.  Can you try that one?

**Comment by DerellLicht** [comment]
Nyet, still the same error:
![TE error](https://github.com/doug24/ThemeEditor/assets/5551606/436065ab-321e-44f2-93f9-9db5f5812ef7)
 
 What's interesting, though, is that if I run the program from *inside the zip file*, it runs fine...
 
 I also tried turning off my anti-virus, just in case; that made no difference.

**Comment by DerellLicht** [comment]
Okay, I figured this out... I had tried, with TE 2.0.0, to copy TE to the dnGrep folder, so both apps would be together...
That failed with the above error...

But if I install TE in my standard stand-alone-apps folder, d:\apps, then it runs just fine...
I don't know why TE doesn't like the dnGrep folder, but this is fine...
